services:
  openclaw-gateway:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    user: "0:0"
    volumes:
      - openclaw-data:/home/node/.openclaw
      - ./config/openclaw.json:/home/node/.openclaw/openclaw.json
      - openclaw-workspace:/home/node/.openclaw/workspace
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "18789",
      ]

  openclaw-cli:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    depends_on:
      - openclaw-gateway
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      BROWSER: echo
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    user: "0:0"
    volumes:
      - openclaw-data:/home/node/.openclaw
      - ./config/openclaw.json:/home/node/.openclaw/openclaw.json
      - openclaw-workspace:/home/node/.openclaw/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]

  browser:
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    environment:
      - TIMEOUT=300000
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  openclaw-data:
  openclaw-workspace:
